export const USER_ROLES = {
  RECEPTION: "RECEPTION",
  DENTIST: "DENTIST",
  XRAY: "XRAY",
};

export const APPOINTMENT_STATUS = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
};

export const TREATMENT_STATUS = {
  PENDING: "PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
};
